### ISSUE TITLE
Uses CreateFromPinnedArray but the array isn't pinned?

### ISSUE THREAD

**Issue by benaadams** [Scooletz/Thruster#1]
https://github.com/Scooletz/Thruster/blob/4667d2226d8ab5122339d8582d75e05ba251b6dd/src/Thruster/FastMemoryPool.cs#L68

Would need to call `GCHandle.Alloc(memory, GCHandleType.Pinned)` on the array to use this method.

(Presumably in constructor saving the result to call `.Free()` in Dispose() on the result)

**Comment by Scooletz** [comment]
That was a leftover from tests I did. I've removed it for now. Thank you for noticing. It might be back though, depending on various usages (yes, I'm looking at Kestrel 😉 )
